# 3.9 FFT

In [50]:
%pylab inline
from pprint import pprint

Populating the interactive namespace from numpy and matplotlib


In [40]:
PI2 = 2 * np.pi

In [41]:
def DFT_matrix(N = 4, decimal = 2):
    
    idx = range(N)
    kn = np.outer(idx, idx)
    W_N = np.exp(-1j * PI2 / N) 
    DFT_matrix = np.round(W_N ** kn, decimal)
    
    return DFT_matrix

In [42]:
DFT_matrix(N = 2)

array([[ 1.+0.j,  1.+0.j],
       [ 1.+0.j, -1.-0.j]])

In [43]:
DFT_matrix(N = 3)

array([[ 1. +0.j  ,  1. +0.j  ,  1. +0.j  ],
       [ 1. +0.j  , -0.5-0.87j, -0.5+0.87j],
       [ 1. +0.j  , -0.5+0.87j, -0.5-0.87j]])

In [44]:
DFT_matrix(N = 4)

array([[ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j],
       [ 1.+0.j,  0.-1.j, -1.-0.j, -0.+1.j],
       [ 1.+0.j, -1.-0.j,  1.+0.j, -1.-0.j],
       [ 1.+0.j, -0.+1.j, -1.-0.j,  0.-1.j]])

In [45]:
DFT_matrix(N = 5)

array([[ 1.  +0.j  ,  1.  +0.j  ,  1.  +0.j  ,  1.  +0.j  ,  1.  +0.j  ],
       [ 1.  +0.j  ,  0.31-0.95j, -0.81-0.59j, -0.81+0.59j,  0.31+0.95j],
       [ 1.  +0.j  , -0.81-0.59j,  0.31+0.95j,  0.31-0.95j, -0.81+0.59j],
       [ 1.  +0.j  , -0.81+0.59j,  0.31-0.95j,  0.31+0.95j, -0.81-0.59j],
       [ 1.  +0.j  ,  0.31+0.95j, -0.81+0.59j, -0.81-0.59j,  0.31-0.95j]])

In [52]:
DFT_matrix(N = 6)

array([[ 1. +0.j  ,  1. +0.j  ,  1. +0.j  ,  1. +0.j  ,  1. +0.j  ,
         1. +0.j  ],
       [ 1. +0.j  ,  0.5-0.87j, -0.5-0.87j, -1. -0.j  , -0.5+0.87j,
         0.5+0.87j],
       [ 1. +0.j  , -0.5-0.87j, -0.5+0.87j,  1. +0.j  , -0.5-0.87j,
        -0.5+0.87j],
       [ 1. +0.j  , -1. -0.j  ,  1. +0.j  , -1. -0.j  ,  1. +0.j  ,
        -1. -0.j  ],
       [ 1. +0.j  , -0.5+0.87j, -0.5-0.87j,  1. +0.j  , -0.5+0.87j,
        -0.5-0.87j],
       [ 1. +0.j  ,  0.5+0.87j, -0.5+0.87j, -1. -0.j  , -0.5-0.87j,
         0.5-0.87j]])

In [47]:
DFT_matrix(N = 7)

array([[ 1.  +0.j  ,  1.  +0.j  ,  1.  +0.j  ,  1.  +0.j  ,  1.  +0.j  ,
         1.  +0.j  ,  1.  +0.j  ],
       [ 1.  +0.j  ,  0.62-0.78j, -0.22-0.97j, -0.9 -0.43j, -0.9 +0.43j,
        -0.22+0.97j,  0.62+0.78j],
       [ 1.  +0.j  , -0.22-0.97j, -0.9 +0.43j,  0.62+0.78j,  0.62-0.78j,
        -0.9 -0.43j, -0.22+0.97j],
       [ 1.  +0.j  , -0.9 -0.43j,  0.62+0.78j, -0.22-0.97j, -0.22+0.97j,
         0.62-0.78j, -0.9 +0.43j],
       [ 1.  +0.j  , -0.9 +0.43j,  0.62-0.78j, -0.22+0.97j, -0.22-0.97j,
         0.62+0.78j, -0.9 -0.43j],
       [ 1.  +0.j  , -0.22+0.97j, -0.9 -0.43j,  0.62-0.78j,  0.62+0.78j,
        -0.9 +0.43j, -0.22-0.97j],
       [ 1.  +0.j  ,  0.62+0.78j, -0.22+0.97j, -0.9 +0.43j, -0.9 -0.43j,
        -0.22-0.97j,  0.62-0.78j]])

In [48]:
DFT_matrix(N = 8)

array([[ 1.  +0.j  ,  1.  +0.j  ,  1.  +0.j  ,  1.  +0.j  ,  1.  +0.j  ,
         1.  +0.j  ,  1.  +0.j  ,  1.  +0.j  ],
       [ 1.  +0.j  ,  0.71-0.71j,  0.  -1.j  , -0.71-0.71j, -1.  -0.j  ,
        -0.71+0.71j, -0.  +1.j  ,  0.71+0.71j],
       [ 1.  +0.j  ,  0.  -1.j  , -1.  -0.j  , -0.  +1.j  ,  1.  +0.j  ,
         0.  -1.j  , -1.  -0.j  , -0.  +1.j  ],
       [ 1.  +0.j  , -0.71-0.71j, -0.  +1.j  ,  0.71-0.71j, -1.  -0.j  ,
         0.71+0.71j,  0.  -1.j  , -0.71+0.71j],
       [ 1.  +0.j  , -1.  -0.j  ,  1.  +0.j  , -1.  -0.j  ,  1.  +0.j  ,
        -1.  -0.j  ,  1.  +0.j  , -1.  -0.j  ],
       [ 1.  +0.j  , -0.71+0.71j,  0.  -1.j  ,  0.71+0.71j, -1.  -0.j  ,
         0.71-0.71j, -0.  +1.j  , -0.71-0.71j],
       [ 1.  +0.j  , -0.  +1.j  , -1.  -0.j  ,  0.  -1.j  ,  1.  +0.j  ,
        -0.  +1.j  , -1.  -0.j  ,  0.  -1.j  ],
       [ 1.  +0.j  ,  0.71+0.71j, -0.  +1.j  , -0.71+0.71j, -1.  -0.j  ,
        -0.71-0.71j,  0.  -1.j  ,  0.71-0.71j]])